net_type: res
train_params:
    epochs: 1000
    use_seed: True
    seed: 2

search_params:
    val_start_epoch: 50
    arch_update_epoch: 25
    sample_policy: prob # prob uniform
    weight_sample_num: 1
    softmax_temp: 0.9

    PRIMITIVES_stack: ['basic_block',
                       'sep_conv_3x3',
                       'dil_conv_3x3',
                       
                       
                        ]
#    PRIMITIVES_stack: [ 'basic_block',
#                        'skip_connect',
#                      ]
    PRIMITIVES_head: ['basic_block',
                      'sep_conv_3x3',
                      'dil_conv_3x3',
                      
                      
                     ]

#    adjoin_connect_nums: [10, 10, 10, 10, 10, 10, 10]
    adjoin_connect_nums: [1,1,1,1,1]
    net_scale:
#        chs: [32,
#            48, 56, 64,
#            72, 96, 128,
#            144, 192, 224, 256, 288,
#            480, 512, 864, 960, 1024]
        chs: [
            32,
            64,
            128,
            256,
            320]

        fm_sizes: [144,
                   72,
                   36,
                   18,
                   9]

#        chs: [ 32,
#             48, 56, 64,
#             72, 96, 112,
#             128, 144, 192, 208, 224,
#             256, 288, 480, 496, 512 ]
#        fm_sizes: [ 128,
#             64, 64, 64,
#             32, 32, 32,
#             16, 16, 16, 16, 16,
#             16, 16, 16, 16, 16 ]
        stage: [0,
            1,
            2,
            3,
            4,5]

#        stage: [ 0,
#                 1, 1, 1,
#                 2, 2, 2,
#                 3, 3, 4,
#                 4, 4, 5, 5, 5,
#                 6 ]
        num_layers: [0,
                     0,
                     0,
                     0,0]

optim:
    last_dim: 320
    init_dim: 32
    bn_momentum: 0.1
    bn_eps: 0.001
    weight:
        init_lr: 0.01
        min_lr: 0.0002
        lr_decay_type: cosine
        momentum: 0.9
        weight_decay: 0.0002
    arch:
        alpha_lr: 0.005
        beta_lr: 0.005
        weight_decay: 0.001

    if_sub_obj: False
    sub_obj:
        type: flops
        skip_reg: True
        log_base: 3500.
        sub_loss_factor: 0.2

    if_resume: False
    resume:
        load_path: ''
        load_epoch: 0

data:
    batch_size: 2
    num_workers: 0
    dataset: abdominal
    train_data_type: img
    val_data_type: img
    patch_dataset: False
    input_size: (1,128,128,128)

