net_type: res
train_params:
    epochs: 1000
    use_seed: True
    seed: 2

search_params:
    val_start_epoch: 40
    arch_update_epoch: 30
    sample_policy: prob # prob uniform
    weight_sample_num: 1
    softmax_temp: 0.9

    PRIMITIVES_stack: ['basic_block',
                       'sep_conv_3x3',
                       'dil_conv_3x3',
                       'skip_connect',
                       'cweight',
                        ]
#    PRIMITIVES_stack: [ 'basic_block',
#                        'skip_connect',
#                      ]
    PRIMITIVES_head: ['basic_block',
                      'sep_conv_3x3',
                      'dil_conv_3x3',
                      'cweight',
                     ]

#    adjoin_connect_nums: [10, 10, 10, 10, 10, 10, 10]
    adjoin_connect_nums: [1,1,1,1]
    net_scale:
#        chs: [32,
#            48, 56, 64,
#            72, 96, 128,
#            144, 192, 224, 256, 288,
#            480, 512, 864, 960, 1024]
        chs: [
            128,
            224, 256,
            496, 512,
            864, 960, 1024 ]

        fm_sizes: [96,
                   48, 48,
                   24, 24,
                   12, 12, 12]

#        chs: [ 32,
#             48, 56, 64,
#             72, 96, 112,
#             128, 144, 192, 208, 224,
#             256, 288, 480, 496, 512 ]
#        fm_sizes: [ 128,
#             64, 64, 64,
#             32, 32, 32,
#             16, 16, 16, 16, 16,
#             16, 16, 16, 16, 16 ]
        stage: [0,
            1, 1,
            2, 2,
            3, 3, 3,
            4]

#        stage: [ 0,
#                 1, 1, 1,
#                 2, 2, 2,
#                 3, 3, 4,
#                 4, 4, 5, 5, 5,
#                 6 ]
        num_layers: [0,
                     4, 2,
                     4, 2,
                     4, 2, 1]

optim:
    last_dim: 1024
    init_dim: 64
    bn_momentum: 0.1
    bn_eps: 0.001
    weight:
        init_lr: 0.0015
        min_lr: 0.0002
        lr_decay_type: cosine
        momentum: 0.9
        weight_decay: 0.0002
    arch:
        alpha_lr: 0.0005
        beta_lr: 0.0005
        weight_decay: 0.001

    if_sub_obj: False
    sub_obj:
        type: flops
        skip_reg: True
        log_base: 3500.
        sub_loss_factor: 0.2

    if_resume: False
    resume:
        load_path: '/hdd1/wyn/DenseNAS/log/20201228-105632-search_res_promise12/output/weights_best.pt'
        load_epoch: 400

data:
    batch_size: 16
    num_workers: 0
    dataset: sliver07
    train_data_type: img
    val_data_type: img
    patch_dataset: False
    input_size: (1,256,256)

